apiVersion: my.api.group/v1alpha1
kind: MyAppResource
metadata:
  labels:
    app.kubernetes.io/name: myappresource
    app.kubernetes.io/instance: whatever
    app.kubernetes.io/part-of: angi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: angi
  name: whatever
spec:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
    limits:
      memory: 64Mi
  image:
    repository: ghcr.io/stefanprodan/podinfo
    tag: latest
  ui:
    color: "#34577c"
    message: "some string"
  redis:
    enabled: true
